import threading

""" Global parameters """
UNUSED = 0
REQUEST = 1
COMMAND = 1
VERSION = 2
TTL = 225
RESPONSE = 2
ROUTE_TAG = 0
RIP_PORT = 520
RIPv2_VERSION = 2
ADDRESS_FAMILY = 2
IP_ADDRESS = 'addr'
SUBNET_MASK = 'netmask'
INFINITY_HOP_COUNT = 16
NEXT_HOP_ZERO = "0.0.0.0"
MAX_NUMBER_OF_ENTRIES = 25
UPDATE_TIME_INTERVAL_SECONDS = 30
LISTEN_ALL_INTERFACES = "0.0.0.0"
IP_MULTI_CAST_ADDRESS = "224.0.0.9"
IPV4_ADDRESS_FAMILY_IDENTIFIER = 2
MAX_NUMBER_OF_RECEIVED_BYTES = 504
INVALID_TIMER_DEFAULT_SECONDS = 35
DEFAULT_TIME_FOR_LOCAL_INTERFACES = 0
SCANNING_INTERFACE_STRING_LENGTH = 40
IGNORE_NETWORK = ("127.0.0.0", "255.0.0.0")

logging_lock = threading.Lock()
routing_table_lock = threading.Lock()
neighbours_lock = threading.Lock()